name: Auto Commit

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'niteshraj2310'
          git config --global user.email 'niteshraj2310@users.noreply.github.com'
      
      - name: Create a blank commit
        run: |
          COMMIT_MESSAGE=$(curl -s https://whatthecommit.com/index.txt)
          git commit --allow-empty -m "$COMMIT_MESSAGE" --signoff
      
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push