name: Advice workflow
on:
  push:
  schedule:
    - cron: "0 */3 * * *" # Run every three hours
  workflow_dispatch:
jobs:
  update-readme-with-quote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: pull script to get quote
        uses: ashutoshkrris/random-advice-workflow@master
      - name: Commit and push changes
        run: |
          git config --local user.email "niteshraj231@outlook.com"
          git config --local user.name "Nitesh"
          git add .
          COMMIT_MESSAGE=$(curl -s https://whatthecommit.com/index.txt)
          git commit -m "$COMMIT_MESSAGE" --signoff || echo "No changes to commit"
          git push